---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: localhost
  ansible_connection: ssh
  ansible_sudo: false
  ansible_verbose: true
  ansible_verbosity: 3
  require_chef_for_busser: false
  enable_yum_epel: true

platforms:
  - name: centos-7

verifier:
  name: serverspec
  patterns:
    - roles/ansible-role-nvm/test/integration/default/serverspec/*_spec.rb
  env_vars:
    TARGET_HOST: localhost
    LOGIN_USER: kitchen
    SSH_KEY: 'roles/ansible-role-nvm/.kitchen/docker_id_rsa'

suites:
  - name: default
