---

- name: install node
  shell: >
    source {{nvm_profile_path}} &&
    if ! nvm ls --no-colors | awk '{print $1$2}' | grep -Eq '^(->)?{{version}}\*?$'; then
      nvm install {{version}} && echo -e \\nchanged
    fi
  args:
    executable: /bin/bash
  register: result
  changed_when: "'changed' in result.stdout_lines"

- name: install npm packages
  shell: >
    source {{nvm_profile_path}} &&
    if ! nvm list | grep -q yarn; then
      npm install --global {{item}} && echo -e \\nchanged
    fi
  args:
    executable: /bin/bash
  register: result
  changed_when: "'changed' in result.stdout_lines"
  with_items: "{{npm_packages}}"

- name: use default version
  shell: "source {{nvm_profile_path}} && nvm use default"
  args:
    executable: /bin/bash
  changed_when: false
