---

- name: install git
  become: yes
  yum: name=git

- name: check out rbenv
  git:
    repo: "{{nvm_repo_url}}"
    dest: "{{nvm_install_path}}"
    version: "{{nvm_version}}"

- name: configure PATH
  blockinfile:
    dest: "{{nvm_profile_path}}"
    marker: "# {mark} ANSIBLE NVM BLOCK"
    block: |
      if [ -d "{{nvm_install_path}}" ]; then
        export NVM_DIR="{{nvm_install_path}}"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
      fi
    follow: yes
